version: '3.4'

services:
  dev:
    image: ms-ml-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    entrypoint:
      - "npm"
    command: ["start"]
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./src:/usr/src/src
  proxy:
    image: ms-ml-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: proxy
    ports:
      - "3666:3666"
    environment:
      - ORIGINS=${ORIGINS}
      - TARGETS=${TARGETS}
    volumes:
      - ./server:/usr/src/server

