version: '3.2'

services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint:
      - "npm"
    command: ["start"]
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ${PWD}:/src
      - /src/node_modules
