version: '3.4'

services:
  dev:
    image: ms-ml-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: builder
    entrypoint:
      - "npm"
    command: ["start"]
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
    volumes:
      - ./src:/usr/src/src
  proxy:
    image: ms-ml-dev:latest
    build:
      context: ./
      dockerfile: Dockerfile
      target: proxy
    ports:
      - "3666:3666"
    environment:
      - URL_FOR_MSML=http://otter.southcentralus.cloudapp.azure.com:6001/v4/camera-trap/detection-batch
      - CAMERA_TRAPS_API_SERVICE_HOST=10.0.244.99
      - CAMERA_TRAPS_API_SERVICE_PATH=/v4/camera-trap/detection-batch
      - ORIGINS=${ORIGINS}
      - TARGETS=${TARGETS}
      - REVISION=fakerevision123
    volumes:
      - ./server:/usr/src/server

