apiVersion: v1
kind: Service
metadata:
  name: subject-assistant-proxy
spec:
  selector:
    app: subject-assistant-proxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3666
  type: NodePort
