name: Deploy to Production

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build_and_push_image:
      name: Build and Push Image
      uses: zooniverse/ci-cd/.github/workflows/build_and_push_image.yaml@main
      with:
        repo_name: subject-assistant
        commit_id: ${{ github.sha }}
        latest: true

  deploy_production:
    name: Deploy to Production
    uses: zooniverse/ci-cd/.github/workflows/deploy_app.yaml@main
    needs: build_and_push_image
    with:
      app_name: subject-assistant
      commit_id: ${{ github.sha }}
      environment: production
    secrets:
      creds: ${{ secrets.AZURE_AKS }}
